//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aXon.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptItem
    {
        public System.Guid Id { get; set; }
        public System.DateTimeOffset CreateDateTime { get; set; }
        public System.DateTimeOffset LastEditDateTime { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.Guid CreatedBy { get; set; }
        public bool IsActiveRecord { get; set; }
        public System.Guid ReceiptId { get; set; }
        public System.Guid PartId { get; set; }
        public int Qty { get; set; }
        public Nullable<System.Guid> PurchaseOrderItemId { get; set; }
    
        public virtual BasePurchaseOrderItem BasePurchaseOrderItem { get; set; }
        public virtual Part Part { get; set; }
        public virtual Receipt Receipt { get; set; }
    }
}
