//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aXon.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorPurchaseOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VendorPurchaseOrder()
        {
            this.VendorPurchaseOrderItems = new HashSet<VendorPurchaseOrderItem>();
        }
    
        public System.Guid Id { get; set; }
        public System.DateTimeOffset CreateDateTime { get; set; }
        public System.DateTimeOffset LastEditDateTime { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.Guid CreatedBy { get; set; }
        public bool IsActiveRecord { get; set; }
        public System.Guid CompanyId { get; set; }
        public System.Guid WarehouseId { get; set; }
        public int PONumber { get; set; }
        public System.Guid VendorId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Vendor Vendor { get; set; }
        public virtual WareHouse WareHouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorPurchaseOrderItem> VendorPurchaseOrderItems { get; set; }
    }
}
