//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aXon.Desktop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class aXonEntities : DbContext
    {
        public aXonEntities()
            : base("name=aXonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<BaseDictionaryModel> BaseDictionaryModels { get; set; }
        public virtual DbSet<BaseModel> BaseModels { get; set; }
        public virtual DbSet<BasePurchaseOrder> BasePurchaseOrders { get; set; }
        public virtual DbSet<BasePurchaseOrderItem> BasePurchaseOrderItems { get; set; }
        public virtual DbSet<Carrier> Carriers { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyBaseModel> CompanyBaseModels { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerContact> CustomerContacts { get; set; }
        public virtual DbSet<CustomerPurchaseOrder> CustomerPurchaseOrders { get; set; }
        public virtual DbSet<CustomerPurchaseOrderItem> CustomerPurchaseOrderItems { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Part> Parts { get; set; }
        public virtual DbSet<PartVendor> PartVendors { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<PersonAddress> PersonAddresses { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<VendorPurchaseOrder> VendorPurchaseOrders { get; set; }
        public virtual DbSet<VendorPurchaseOrderItem> VendorPurchaseOrderItems { get; set; }
        public virtual DbSet<WareHouse> WareHouses { get; set; }
        public virtual DbSet<WarehouseBaseModel> WarehouseBaseModels { get; set; }
    }
}
